---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: trunks
  name: trunk
  entry: trunk fmt
  description: runs trunk.io (and you should too)
  types_or:
      [
          asm,
          bash,
          c,
          c++,
          dockerfile,
          header,
          json,
          makefile,
          manifest,
          markdown,
          powershell,
          python,
          python3,
          yaml,
      ]
  language: node
